title                   : Slinky
repo                    : https://github.com/ReactivePixels/slinky
version                 : 0.0.0
src                     : src
theme                   : src/themes/swanky-docs-theme
output                  : docs
serverPath              : get-slinky

sections                :

  - title               : Welcome
    content             : src/content/**/*.*
